"""rename_interactions_count

Revision ID: b249b7afe0c1
Revises: 7277a01dd82b
Create Date: 2023-12-03 23:27:44.874721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b249b7afe0c1'
down_revision = '7277a01dd82b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anonymous_user', sa.Column('num_visits', sa.Integer(), nullable=True))
    op.drop_column('anonymous_user', 'interactions_count')
    op.add_column('user', sa.Column('num_visits', sa.Integer(), nullable=True))
    op.drop_column('user', 'interactions_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('interactions_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('user', 'num_visits')
    op.add_column('anonymous_user', sa.Column('interactions_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('anonymous_user', 'num_visits')
    # ### end Alembic commands ###
